const fs = require("fs");

const CONTENTS = {
  OUTLINE: {},
  SOLID: {},
  HEAD: {},
  TAIL: "",
};

const subDirs = ["24/outline", "24/solid"];

subDirs.forEach((subDir) => {
  const path = `./node_modules/heroicons/${subDir}/`;
  const fileNames = fs.readdirSync(path);
  const SUBDIR = subDir.replace('24/','');

  const object = CONTENTS[SUBDIR.toUpperCase()];

  fileNames.forEach((filename) => {
    const contents = fs
      .readFileSync(path + filename)
      .toString()
      .trimEnd();
    const lines = contents.split("\n");
    if (!CONTENTS.HEAD[SUBDIR]) {
      CONTENTS.HEAD[SUBDIR] = lines[0].replace(/ aria-hidden="true"/g, "");
    }
    if (!CONTENTS.TAIL) {
      CONTENTS.TAIL = lines[lines.length - 1];
    }
    const guts = lines
      .slice(1, lines.length - 1)
      .join("")
      .replace(/\ \ /g, "");
    if (object) object[filename.slice(0, -4)] = guts;
  });
});

fs.writeFileSync(
  "./icons.js",
  `// This file was generated by build.js at ${new Date().toISOString()}\n\nmodule.exports = ${JSON.stringify(
    CONTENTS
  )};\n`
);
